[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "nanobrain"
description = "nanobrain"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "braceexpand",
    "datasets",
    "einops",
    "flask",
    "fsspec",
    "huggingface-hub",
    "jaxtyping",
    "matplotlib",
    "nibabel",
    "numpy",
    "omegaconf",
    "pandas",
    "pyyaml",
    "s3fs",
    "scikit-image",
    "scikit-learn",
    "scipy",
    "tabulate",
    "templateflow",
    "timm",
    "torch==2.9.1",
    "torchvision",
    "tqdm",
    "wandb",
    "webdataset",
]

[dependency-groups]
dev = [
    "ipython",
    "jupyter",
    "matplotlib",
    "pre-commit",
    "pytest",
    "python-dotenv",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
ignore = ["F722"]
